#:kivy 1.11.1
#:import utils kivy.utils

<Graphics>:

    Label:
        font_size: 70
        center_x: root.width/2
        top: root.top - 50
        text: "Welcome"


    Button:
        size:(200,200)
        size_hint:(None,None)
        text:"START"
        center_x: root.width/2
        center_y: root.height/2
        on_press: root.say_hello()
        background_normal: ''
        background_color: 1, .3, .4, .85
